package com.mas.recomm.agent.recommbuilder;

import java.sql.ResultSet;
import java.util.List;

import org.apache.mahout.cf.taste.recommender.RecommendedItem;

import com.mas.recomm.model.RecommendedMovieItem;

import jadex.commons.future.IFuture;

public interface IRecommendationBuildService {
	
	/**
	 * 
	 * @param mahoutres  A list of mahout recommendation result, only has id and preference filed
	 * @param searchres  The search result generated by SearchBDI agent 
	 * @return List<RecommendedMovieItem>
	 */
	public IFuture<List<RecommendedMovieItem>> buildRecommendationRes(List<RecommendedItem> mahoutres, ResultSet searchres);

}
