package com.mas.recomm.agent.recommbuilder;

import java.sql.ResultSet;
import java.util.List;

import org.apache.mahout.cf.taste.recommender.RecommendedItem;

import com.mas.recomm.model.RecommendedMovieItem;

import jadex.commons.future.IFuture;

public interface IRecommendationBuildService {
	
	/**
	 * 
	 * @param params[0] miningRes  A list of mahout recommendation result, only has id and preference filed
	 *        params[1] searchRes  The search result generated by SearchBDI agent 
	 * @return List<RecommendedMovieItem>
	 */
	public IFuture<List<RecommendedMovieItem>> buildRecommendationRes(List[] params);

}
